# Generated by Django 4.2 on 2023-04-14 11:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('fileupload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filedata',
            name='is_words',
        ),
    ]
